name: jour2
on:
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: pip install -r requirements.txt
      - name: Generate 50
        run: python src/generate_paris50.py --urls urls.txt --out data/raw_data.json --target 50
      - name: Clean
        run: python src/cleaner.py --input data/raw_data.json --output data/cleaned_data.csv
      - name: Validate
        run: python src/validate.py --csv data/cleaned_data.csv --min_rows 50
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: jour2-artifacts
          path: |
            data/raw_data.json
            data/cleaned_data.csv
